# Generated by Django 2.2.3 on 2019-08-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190819_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='headshot',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
