# Generated by Django 2.2.3 on 2019-08-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190819_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='headshot',
            field=models.ImageField(upload_to='store/static/img/'),
        ),
    ]
