# Generated by Django 2.2.3 on 2020-04-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200315_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_name',
            new_name='Customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='g_costprice',
            new_name='Gift_costprice',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='g_name',
            new_name='Gift_name',
        ),
        migrations.RenameField(
            model_name='gift_type',
            old_name='g_description',
            new_name='Gift_description',
        ),
        migrations.RenameField(
            model_name='gift_type',
            old_name='g_type',
            new_name='Gift_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='c_phno',
            new_name='Total_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='c_phno',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='g_gifttype',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='t_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='t_paymode',
        ),
        migrations.AddField(
            model_name='customer',
            name='Phone',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='gift',
            name='Gift_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.gift_type', verbose_name='Giftype'),
        ),
        migrations.AddField(
            model_name='order',
            name='Customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.customer', verbose_name='Customername'),
        ),
        migrations.AddField(
            model_name='order',
            name='Gift_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.gift', verbose_name='Giftname'),
        ),
    ]
