# Generated by Django 2.2.3 on 2020-04-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200424_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='headshot',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
