# Generated by Django 2.2.3 on 2020-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200424_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='Customer_name',
            field=models.CharField(max_length=30),
        ),
    ]
